# ***`[ üåè  Abdiabyev Jasurbek](https://t.me/abd1bayev)`***

# ***Pandas kutubxonasi:***
# Ma'lumotlar olimlari uchun ma'lumotlarni manipulyatsiya qilish va tahlil qilish uchun eng ko'p afzal qilingan vositalardan biri bo'lib, ma'lumotlarni vizualizatsiya qilish uchun matplotlib va ‚Äã‚ÄãPandas qurilgan Python-da ilmiy hisoblash uchun fundamental kutubxona bo'lgan  NumPy yonida.** 

# ***Tez, moslashuvchan va ifodali Pandas ma'lumotlar tuzilmalari haqiqiy dunyo ma'lumotlarini tahlil qilishni sezilarli darajada osonlashtirish uchun mo'ljallangan, ammo bu uni endi boshlayotganlar uchun darhol bo'lmasligi mumkin. Ushbu paketga juda ko'p funksiyalar kiritilganligi sababli, variantlar juda ko'p.***

# ***Aynan shu erda Pandas cheat varaqlari foydali bo'lishi mumkin. ***

# ***Bu Pandas asoslari bo ªyicha tezkor qo ªllanma bo ªlib, siz Python bilan ma ºlumotlaringiz bilan kurashishni boshlashingiz kerak bo ªladi. ***

# ***Shunday qilib, agar siz Pandas bilan ma'lumotlar fanlari bo'yicha sayohatni endi boshlayotgan bo'lsangiz yoki hali boshlamaganlar uchun uni o'rganishni osonlashtirish uchun qo'llanma sifatida ishlatishingiz mumkin. haqida va undan foydalaning. ***

# ***Python-da ma'lumotlar faniga oid Pandas Cheat Sheet***

# ***Pandas firibgarlik varaqasi sizga Pandas kutubxonasi asoslari bo ªyicha yo ªl-yo ªriq ko ªrsatadi, ma ºlumotlar tuzilmalaridan kiritish-chiqarish, tanlash, indekslar yoki ustunlarni tushirish, saralash va tartiblash, qo ªllash uchun siz ishlayotgan ma ºlumotlar tuzilmalarining asosiy ma ºlumotlarini olish. funktsiyalari va ma'lumotlarni moslashtirish.***

# ***Muxtasar qilib aytganda, Python bilan ma'lumotlar fanini o'rganishni boshlash uchun kerak bo'lgan hamma narsa!***

# ***Ko'proq o'rganishni xohlaysizmi? Intermediate Python For Data Science kursini hozir bepul boshlang yoki Pandas DataFrame o ªquv qo ªllanmamizni sinab ko ªring ! ***

![Pandas_Cheat_Sheet_for_Data_Science_in_Python_hqirhp.webp]()

In [ ]:
import pandas as pd

# ***Pandas ma'lumotlar tuzilmalari***
# Seriya
# ***Har qanday ma'lumot turini saqlashga qodir bo'lgan bir o'lchovli etiketli massiv***

In [ ]:
s = pd.Series([3, -5, 7, 4], index=['a','b','c','d'])
s

a    3
b   -5
c    7
d    4
dtype: int64

# ***DataFrame***
# ***Potensial har xil turdagi ustunlarga ega bo'lgan ikki o'lchovli etiketli ma'lumotlar strukturasi***

In [ ]:
data = {'Country': ['Belgium', 'India', 'Brazil'],
        'Capital': ['Brussels', 'New Delhi', 'Brasilia'],
        'Population': [11190846, 1303171035, 207847528]}

df = pd.DataFrame(data,columns=['Country', 'Capital', 'Population'])
df

   Country    Capital  Population
0  Belgium   Brussels    11190846
1    India  New Delhi  1303171035
2   Brazil   Brasilia   207847528

# ***Yordam so'rash***

In [ ]:
help(pd.Series.loc)

Help on property:

    Access a group of rows and columns by label(s) or a boolean array.

    ``.loc[]`` is primarily label based, but may also be used with a
    boolean array.

    Allowed inputs are:

    - A single label, e.g. ``5`` or ``'a'``, (note that ``5`` is
      interpreted as a *label* of the index, and **never** as an
      integer position along the index).
    - A list or array of labels, e.g. ``['a', 'b', 'c']``.
    - A slice object with labels, e.g. ``'a':'f'``.

      .. warning:: Note that contrary to usual python slices, **both** the
          start and the stop are included

    - A boolean array of the same length as the axis being sliced,
      e.g. ``[True, False, True]``.
    - An alignable boolean Series. The index of the key will be aligned before
      masking.
    - An alignable Index. The Index of the returned selection will be the input.
    - A ``callable`` function with one argument (the calling Series or
      DataFrame) and that returns valid output for indexing (one of the above)

    See more at :ref:`Selection by Label <indexing.label>`.

    Raises
    ------
    KeyError
        If any items are not found.
    IndexingError
        If an indexed key is passed and its index is unalignable to the frame index.

    See Also
    --------
    DataFrame.at : Access a single value for a row/column label pair.
    DataFrame.iloc : Access group of rows and columns by integer position(s).
    DataFrame.xs : Returns a cross-section (row(s) or column(s)) from the
        Series/DataFrame.
    Series.loc : Access group of values using labels.

    Examples
    --------
    **Getting values**

    >>> df = pd.DataFrame([[1, 2], [4, 5], [7, 8]],
    ...      index=['cobra', 'viper', 'sidewinder'],
    ...      columns=['max_speed', 'shield'])
    >>> df
                max_speed  shield
    cobra               1       2
    viper               4       5
    sidewinder          7       8

    Single label. Note this returns the row as a Series.

    >>> df.loc['viper']
    max_speed    4
    shield       5
    Name: viper, dtype: int64

    List of labels. Note using ``[[]]`` returns a DataFrame.

    >>> df.loc[['viper', 'sidewinder']]
                max_speed  shield
    viper               4       5
    sidewinder          7       8

    Single label for row and column

    >>> df.loc['cobra', 'shield']
    2

    Slice with labels for row and single label for column. As mentioned
    above, note that both the start and stop of the slice are included.

    >>> df.loc['cobra':'viper', 'max_speed']
    cobra    1
    viper    4
    Name: max_speed, dtype: int64

    Boolean list with the same length as the row axis

    >>> df.loc[[False, False, True]]
                max_speed  shield
    sidewinder          7       8

    Alignable boolean Series:

    >>> df.loc[pd.Series([False, True, False],
    ...        index=['viper', 'sidewinder', 'cobra'])]
                max_speed  shield
    sidewinder          7       8

    Index (same behavior as ``df.reindex``)

    >>> df.loc[pd.Index(["cobra", "viper"], name="foo")]
           max_speed  shield
    foo
    cobra          1       2
    viper          4       5

    Conditional that returns a boolean Series

    >>> df.loc[df['shield'] > 6]
                max_speed  shield
    sidewinder          7       8

    Conditional that returns a boolean Series with column labels specified

    >>> df.loc[df['shield'] > 6, ['max_speed']]
                max_speed
    sidewinder          7

    Callable that returns a boolean Series

    >>> df.loc[lambda df: df['shield'] == 8]
                max_speed  shield
    sidewinder          7       8

    **Setting values**

    Set value for all items matching the list of labels

    >>> df.loc[['viper', 'sidewinder'], ['shield']] = 50
    >>> df
                max_speed  shield
    cobra               1       2
    viper               4      50
    sidewinder          7      50

    Set value for an entire row

    >>> df.loc['cobra'] = 10
    >>> df
                max_speed  shield
    cobra              10      10
    viper               4      50
    sidewinder          7      50

    Set value for an entire column

    >>> df.loc[:, 'max_speed'] = 30
    >>> df
                max_speed  shield
    cobra              30      10
    viper              30      50
    sidewinder         30      50

    Set value for rows matching callable condition

    >>> df.loc[df['shield'] > 35] = 0
    >>> df
                max_speed  shield
    cobra              30      10
    viper               0       0
    sidewinder          0       0

    **Getting values on a DataFrame with an index that has integer labels**

    Another example using integers for the index

    >>> df = pd.DataFrame([[1, 2], [4, 5], [7, 8]],
    ...      index=[7, 8, 9], columns=['max_speed', 'shield'])
    >>> df
       max_speed  shield
    7          1       2
    8          4       5
    9          7       8

    Slice with integer labels for rows. As mentioned above, note that both
    the start and stop of the slice are included.

    >>> df.loc[7:9]
       max_speed  shield
    7          1       2
    8          4       5
    9          7       8

    **Getting values with a MultiIndex**

    A number of examples using a DataFrame with a MultiIndex

    >>> tuples = [
    ...    ('cobra', 'mark i'), ('cobra', 'mark ii'),
    ...    ('sidewinder', 'mark i'), ('sidewinder', 'mark ii'),
    ...    ('viper', 'mark ii'), ('viper', 'mark iii')
    ... ]
    >>> index = pd.MultiIndex.from_tuples(tuples)
    >>> values = [[12, 2], [0, 4], [10, 20],
    ...         [1, 4], [7, 1], [16, 36]]
    >>> df = pd.DataFrame(values, columns=['max_speed', 'shield'], index=index)
    >>> df
                         max_speed  shield
    cobra      mark i           12       2
               mark ii           0       4
    sidewinder mark i           10      20
               mark ii           1       4
    viper      mark ii           7       1
               mark iii         16      36

    Single label. Note this returns a DataFrame with a single index.

    >>> df.loc['cobra']
             max_speed  shield
    mark i          12       2
    mark ii          0       4

    Single index tuple. Note this returns a Series.

    >>> df.loc[('cobra', 'mark ii')]
    max_speed    0
    shield       4
    Name: (cobra, mark ii), dtype: int64

    Single label for row and column. Similar to passing in a tuple, this
    returns a Series.

    >>> df.loc['cobra', 'mark i']
    max_speed    12
    shield        2
    Name: (cobra, mark i), dtype: int64

    Single tuple. Note using ``[[]]`` returns a DataFrame.

    >>> df.loc[[('cobra', 'mark ii')]]
                   max_speed  shield
    cobra mark ii          0       4

    Single tuple for the index with a single label for the column

    >>> df.loc[('cobra', 'mark i'), 'shield']
    2

    Slice from index tuple to single label

    >>> df.loc[('cobra', 'mark i'):'viper']
                         max_speed  shield
    cobra      mark i           12       2
               mark ii           0       4
    sidewinder mark i           10      20
               mark ii           1       4
    viper      mark ii           7       1
               mark iii         16      36

    Slice from index tuple to index tuple

    >>> df.loc[('cobra', 'mark i'):('viper', 'mark ii')]
                        max_speed  shield
    cobra      mark i          12       2
               mark ii          0       4
    sidewinder mark i          10      20
               mark ii          1       4
    viper      mark ii          7       1

# ***I/U***
# ***CSV-ga o'qing va yozing***

In [ ]:
pd.read_csv('test.csv', header=None, nrows=5)

# ***Bitta fayldan bir nechta varaqlarni o'qing***

In [ ]:
xlsx = pd.ExcelFile('file.xls')
df = pd.read_excel(xlsx, 'Sheet1')

# ***Excelga o'qish va yozish***

In [ ]:
pd.read_excel('file.xlsx')
df.to_excel('dir/myDataFrame.xlsx', sheet_name='Sheet1')

# ***SQL so'rovi yoki ma'lumotlar bazasi jadvaliga o'qish va yozish***

# **(read_sql() bu read_sql_table() va read_sql_query() atrofidagi qulaylik paketidir)**

In [ ]:
from sqlalchemy import create_engine

In [ ]:
engine = create_engine('sqlite:///:memory:')

In [ ]:
pd.read_sql(SELECT * FROM my_table;, engine)

In [ ]:
pd.read_sql_table('my_table', engine)

In [ ]:
pd.read_sql_query(SELECT * FROM my_table;', engine)

In [ ]:
df.to_sql('myDf', engine)

# ***Tanlash***
# Olish

*Bitta* elementni oling

In [ ]:
s['b']

-5

# ***DataFrame to'plamini oling***

In [ ]:
df[1:]

  Country    Capital  Population
1   India  New Delhi  1303171035
2  Brazil   Brasilia   207847528

# ***Tanlash', Mantiqiy indekslash va sozlash***
# Lavozim bo'yicha
# **Satr va ustun bo'yicha bitta qiymatni tanlang**

In [ ]:
df.iloc([0], [0])

In [ ]:
df.iat([0], [0])

# ***Qator va ustunlarni tanlang***

In [ ]:
df.ix[1, 'Capital']

# ***Mantiqiy indekslash***
## *Qiymati >1 bo'lmagan s seriyasi*

In [ ]:
s[~(s > 1)]

b   -5
dtype: int64

# ***s bu yerda qiymat <-1 yoki >2***

In [ ]:
s[(s < -1)| (s > 2)]

a    3
b   -5
c    7
d    4
dtype: int64

# ***DataFrame-ni sozlash uchun filtrdan foydalaning***

In [ ]:
df[df['Population']>1200000000]

  Country    Capital  Population
1   India  New Delhi  1303171035

# ***Sozlama***
# **s seriyasining a indeksini 6 ga o'rnating**

In [ ]:
s['a'] = 6
s

a    6
b   -5
c    7
d    4
dtype: int64

# ***Tutish***
# **Qatorlardan qiymatlarni tushirish (eksa=0)**

In [ ]:
s.drop(['a', 'c'])

b   -5
d    4
dtype: int64

# **Ustunlardan qiymatlarni tushirish (eksa = 1)**

In [ ]:
df.drop('Country', axis=1)

     Capital  Population
0   Brussels    11190846
1  New Delhi  1303171035
2   Brasilia   207847528

# ***Saralash va tartiblash***
# **O'q bo'ylab teglar bo'yicha saralash**

In [ ]:
df.sort_index()

   Country    Capital  Population
0  Belgium   Brussels    11190846
1    India  New Delhi  1303171035
2   Brazil   Brasilia   207847528

# O'q bo'ylab qiymatlar bo'yicha **tartiblang**

In [ ]:
df.sort_values(by='Country')

   Country    Capital  Population
0  Belgium   Brussels    11190846
2   Brazil   Brasilia   207847528
1    India  New Delhi  1303171035

# Yozuvlarga darajalarni belgilang

In [ ]:
df.rank()

   Country  Capital  Population
0      1.0      2.0         1.0
1      3.0      3.0         3.0
2      2.0      1.0         2.0

# ***Series/DataFrame ma'lumotlarini olish***

# **Asosiy ma'lumotlar**

# (satrlar, ustunlar)

In [ ]:
df.shape

(3, 3)

# Indeksni tavsiflang

In [ ]:
df.index

RangeIndex(start=0, stop=3, step=1)

# DataFrame ustunlarini tavsiflang

In [ ]:
df.columns

Index(['Country', 'Capital', 'Population'], dtype='object')

# DataFrame haqida ma'lumot

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Country     3 non-null      object
 1   Capital     3 non-null      object
 2   Population  3 non-null      int64
dtypes: int64(1), object(2)
memory usage: 200.0+ bytes

# NA bo'lmagan qiymatlar soni

In [ ]:
df.count()

Country       3
Capital       3
Population    3
dtype: int64

# ***Xulosa***
# **Qadriyatlar yig'indisi**

In [ ]:
df.sum()

Country              BelgiumIndiaBrazil
Capital       BrusselsNew DelhiBrasilia
Population                   1522209409
dtype: object

# Qiymatlarning yig'indisi

In [ ]:
df.cumsum()

              Country                    Capital  Population
0             Belgium                   Brussels    11190846
1        BelgiumIndia          BrusselsNew Delhi  1314361881
2  BelgiumIndiaBrazil  BrusselsNew DelhiBrasilia  1522209409

# Minimal/maksimal qiymatlar

In [ ]:
df.min()

Country        Belgium
Capital       Brasilia
Population    11190846
dtype: object

In [ ]:
df.max()

Country            India
Capital        New Delhi
Population    1303171035
dtype: object

# Minimal/Maksimal indeks qiymati

In [ ]:
df.idxmin()
df.idxmex()

# Xulosa statistikasi

In [ ]:
df.describe()

         Population
count  3.000000e+00
mean   5.074031e+08
std    6.961346e+08
min    1.119085e+07
25%    1.095192e+08
50%    2.078475e+08
75%    7.555093e+08
max    1.303171e+09

# Qadriyatlar o'rtacha

In [ ]:
df.mean()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  """Entry point for launching an IPython kernel.

Population    5.074031e+08
dtype: float64

## Qiymatlar medianasi

In [ ]:
df.median()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  """Entry point for launching an IPython kernel.

Population    207847528.0
dtype: float64

# ***Funktsiyalarni qo'llash***

In [ ]:
f = lambda x: x*2
f

# Funktsiyani qo'llash

In [ ]:
df.apply(f)

          Country             Capital  Population
0  BelgiumBelgium    BrusselsBrussels    22381692
1      IndiaIndia  New DelhiNew Delhi  2606342070
2    BrazilBrazil    BrasiliaBrasilia   415695056

# Funktsiyani element bo'yicha qo'llang

In [ ]:
df.applymap(f)

          Country             Capital  Population
0  BelgiumBelgium    BrusselsBrussels    22381692
1      IndiaIndia  New DelhiNew Delhi  2606342070
2    BrazilBrazil    BrasiliaBrasilia   415695056

# ***Ichki ma'lumotlarni moslashtirish***
# NA qiymatlari bir-biriga mos kelmaydigan indekslarda kiritiladi:

In [ ]:
s3 = pd.Series([7,-2,3], index=['a', 'c', 'd'])
s + s3

a    13.0
b     NaN
c     5.0
d     7.0
dtype: float64

# ***To'ldirish usullari bilan arifmetik amallar***

# Shuningdek, siz to'ldirish usullari yordamida ichki ma'lumotlarni moslashtirishni o'zingiz qilishingiz mumkin:

In [ ]:
s.add(s3, fill_value=0)

a    13.0
b    -5.0
c     5.0
d     7.0
dtype: float64

In [ ]:
s.sub(s3, fill_value=2)
s.sub(s3, fill_value=4)
s.sub(s3, fill_value=3)

a   -1.0
b   -7.0
c    9.0
d    1.0
dtype: float64

# ***Thank you all!***